spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: billing-db
      username: admin
      password: admin


service:
  api:
    client:
      customer: http://localhost:8081
      payment: http://localhost:8082